version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
      - run:
          name: Deploy Over SSH
          command: |
            ssh ubuntu@ec2-34-212-27-73.us-west-2.compute.amazonaws.com "cd /home/ubuntu/CIRCLE-CI-MYPASS-FRONTEND && git clone https://github.com/nitro-neal/mypass-frontend-throwaway.git && cd /home/ubuntu/CIRCLE-CI-MYPASS-FRONTEND/mypass-frontend-throwaway && forever start -c 'serve -l 3000 -s' build"
workflows:
  build-and-test:
    jobs:
      - build-and-test
